routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// CONTROLLERS
use App\Http\Controllers\DataTableController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductSimpleController;
use App\Http\Controllers\ProductBundleController;
use App\Http\Controllers\ProductVariantController;
use App\Http\Controllers\ProductGalleriesController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CouponController;
use App\Http\Controllers\VoucherController;
use App\Http\Controllers\BitlyController;
use App\Http\Controllers\VimeoController;
use App\Http\Controllers\EmailController;
use App\Http\Controllers\PdfController;
use App\Http\Controllers\ExportController;
use App\Http\Controllers\ImportController;
use App\Http\Controllers\DOSpacesController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/

// Limit User Registration Entry
if( config('app.LIVE_MODE') == true ) {
  Auth::routes([ 'register' => true, 'verify'  => true, ]);
} else {
  Auth::routes([ 'register' => false, 'verify' => false, ]); // CHANGE BACK TO FALSE WHEN READY
}

// In some cases laravel 301 redirect user to /home
// Chrome issue not laravel issue
Route::get('/home', function() {
  return redirect()->route('home.index');
});

// Frontend routes
if( config('app.LIVE_MODE') == true ) {
  
  // Home Page
  Route::get('/', [PageController::class, 'index'])->name('home.index');

  // Shop Page
  Route::get('/shop', [PageController::class, 'renderShopPage'])->name('shop.index');

  // Single Product Page
  Route::get('/products/single', [PageController::class, 'renderSingleProductPage'])->name('products.single.index');


  
  // My Account Page
  Route::prefix('my-account')->middleware(['auth'])->group( function() {

    //  My Account Dashboard
    Route::get('/', [PageController::class, 'renderMyAccountPage'])->name('myaccount.index');

  });
  


} else {
  // HIDE accessible routes if coming soon / under maintenance
  Route::get('/', [PageController::class, 'renderComingSoonPage'])->name('home.index');
}


/*
|--------------------------------------------------------------------------
| Dashboard Routes
|--------------------------------------------------------------------------
*/

if ( config('app.ALLOW_DASHBOARD') == true ) {

  Route::prefix('my-dashboard')->middleware(['auth', 'role:SUPER_ADMIN'])->group( function() {

    // DASHBOARD
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard.home.index');
    
    // SLUGIFY :: AJAX Only
    Route::get('/slugify/{name}', function($name) {
      if( $request->ajax() ) {
        return unicode_slugify($name);
      } 
      die();
    })->name('dashboard.slugify');
    

    /*
    |--------------------------------------------------------------------------
    | PRODUCTS MANAGEMENT
    |--------------------------------------------------------------------------
    */

    // PRODUCTS
    Route::get('/products', [ProductController::class, 'index'])->name('dashboard.products.index');
    Route::get('/products/create', [ProductController::class, 'create'])->name('dashboard.products.create');
    Route::post('/products/store', [ProductController::class, 'store'])->name('dashboard.products.store');
    Route::get('/products/{id}/edit', [ProductController::class, 'edit'])->name('dashboard.products.edit');
    Route::put('/products/{id}/update', [ProductController::class, 'update'])->name('dashboard.products.update');
    Route::get('/products/{id}/destroy', [ProductController::class, 'destroy'])->name('dashboard.products.destroy');
    
    // PRODUCTS - SIMPLE
    Route::get('/products/simples', [ProductSimpleController::class, 'index'])->name('dashboard.products.simples.index');
    Route::get('/products/simples/create', [ProductSimpleController::class, 'create'])->name('dashboard.products.simples.create');
    Route::post('/products/simples/store', [ProductSimpleController::class, 'store'])->name('dashboard.products.simples.store');
    Route::get('/products/simples/{id}/show', [ProductSimpleController::class, 'show'])->name('dashboard.products.simples.show');
    Route::get('/products/simples/{id}/edit', [ProductSimpleController::class, 'edit'])->name('dashboard.products.simples.edit');
    Route::put('/products/simples/{id}/update', [ProductSimpleController::class, 'update'])->name('dashboard.products.simples.update');
    Route::get('/products/simples/{id}/destroy', [ProductSimpleController::class, 'destroy'])->name('dashboard.products.simples.destroy');
    // AJAX DATA TABLE
    Route::get('/products/simples/fetch_data', [ProductSimpleController::class, 'fetch_data'])->name('dashboard.products.simples.fetch_data');
    
    // PRODUCTS - BUNDLED
    Route::get('/products/bundles', [ProductBundleController::class, 'index'])->name('dashboard.products.bundles.index');
    Route::get('/products/bundles/create', [ProductBundleController::class, 'create'])->name('dashboard.products.bundles.create');
    Route::post('/products/bundles/store', [ProductBundleController::class, 'store'])->name('dashboard.products.bundles.store');
    Route::get('/products/bundles/{id}/show', [ProductBundleController::class, 'show'])->name('dashboard.products.bundles.show');
    Route::get('/products/bundles/{id}/edit', [ProductBundleController::class, 'edit'])->name('dashboard.products.bundles.edit');
    Route::put('/products/bundles/{id}/update', [ProductBundleController::class, 'update'])->name('dashboard.products.bundles.update');
    Route::get('/products/bundles/{id}/destroy', [ProductBundleController::class, 'destroy'])->name('dashboard.products.bundles.destroy');
    // AJAX DATA TABLE
    Route::get('/products/bundles/fetch_data', [ProductBundleController::class, 'fetch_data'])->name('dashboard.products.bundles.fetch_data');
    
    // PRODUCTS - VARIANT
    Route::get('/products/variants', [ProductVariantController::class, 'index'])->name('dashboard.products.variants.index');
    Route::get('/products/variants/create', [ProductVariantController::class, 'create'])->name('dashboard.products.variants.create');
    Route::post('/products/variants/store', [ProductVariantController::class, 'store'])->name('dashboard.products.variants.store');
    Route::get('/products/variants/{id}/show', [ProductVariantController::class, 'show'])->name('dashboard.products.variants.show');
    Route::get('/products/variants/{id}/edit', [ProductVariantController::class, 'edit'])->name('dashboard.products.variants.edit');
    Route::put('/products/variants/{id}/update', [ProductVariantController::class, 'update'])->name('dashboard.products.variants.update');
    Route::get('/products/variants/{id}/destroy', [ProductVariantController::class, 'destroy'])->name('dashboard.products.variants.destroy');
    Route::get('/products/variations/{id}/destroy', [ProductVariantController::class, 'destroy_variation'])->name('dashboard.products.variations.destroy');
    // AJAX DATA TABLE
    Route::get('/products/variants/fetch_data', [ProductVariantController::class, 'fetch_data'])->name('dashboard.products.variants.fetch_data');
    
    // PRODUCT - GALLERY
    Route::get('/products/galleries/{id}/destroy', [ProductGalleriesController::class, 'destroy'])->name('dashboard.products.galleries.destroy');
    
    
    /*
    |--------------------------------------------------------------------------
    | BRANDS MANAGEMENT
    |--------------------------------------------------------------------------
    */
    
    // BRANDS
    Route::get('/brands', [BrandController::class, 'index'])->name('dashboard.brands.index');
    Route::get('/brands/create', [BrandController::class, 'create'])->name('dashboard.brands.create');
    Route::post('/brands/store', [BrandController::class, 'store'])->name('dashboard.brands.store');
    Route::get('/brands/{id}/edit', [BrandController::class, 'edit'])->name('dashboard.brands.edit');
    Route::put('/brands/{id}/update', [BrandController::class, 'update'])->name('dashboard.brands.update');
    Route::get('/brands/{id}/destroy', [BrandController::class, 'destroy'])->name('dashboard.brands.destroy');
    // AJAX DATA TABLE
    Route::get('/brands/fetch_data', [BrandController::class, 'fetch_data'])->name('dashboard.brands.fetch_data');
    
    
    /*
    |--------------------------------------------------------------------------
    | CATEGORIES MANAGEMENT
    |--------------------------------------------------------------------------
    */
    
    // CATEGORIES
    Route::get('/categories', [CategoryController::class, 'index'])->name('dashboard.categories.index');
    Route::get('/categories/create', [CategoryController::class, 'create'])->name('dashboard.categories.create');
    Route::post('/categories/store', [CategoryController::class, 'store'])->name('dashboard.categories.store');
    Route::get('/categories/{id}/edit', [CategoryController::class, 'edit'])->name('dashboard.categories.edit');
    Route::put('/categories/{id}/update', [CategoryController::class, 'update'])->name('dashboard.categories.update');
    Route::get('/categories/{id}/destroy', [CategoryController::class, 'destroy'])->name('dashboard.categories.destroy');
    // AJAX DATA TABLE
    Route::get('/categories/fetch_data', [CategoryController::class, 'fetch_data'])->name('dashboard.categories.fetch_data');
    
    
    /*
    |--------------------------------------------------------------------------
    | VOUCHERS MANAGEMENT
    |--------------------------------------------------------------------------
    */
    
    // VOUCHERS
    Route::get('/vouchers', [VoucherController::class, 'index'])->name('dashboard.vouchers.index');
    Route::get('/vouchers/create', [VoucherController::class, 'create'])->name('dashboard.vouchers.create');

app/Models/Brand.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Brand extends Model {
    
  use HasFactory;

  protected $fillable = [
    'name',
    'slug',
    'status',
    'image',
  ];

  public function skus() {
    return $this->hasMany(ProductSku::class);
  }

  public function products() {
    return $this->hasManyThrough(Product::class, ProductSku::class, 'brand_id', 'sku_id', 'id', 'id');
  }
  
  
  // ACCESSORS
  public function getTheImageAttribute() {
    return (!$this->image) ? asset('dashboard/assets/images/placeholder.jpeg') : asset('storage') . "/" . $this->image ;
  }
  
}

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model {
  
  use HasFactory;

  protected $fillable = [
    'name',
    'slug',
    'parent_id',
    'image',
  ];

  public function parent() {
    return $this->belongsTo(Category::class, 'parent_id');
  }

  public function products() {
    return $this->belongsToMany(Product::class);
  }

  public function voucher_restrictions() {
    return $this->hasMany(VoucherProductCategoryRestriction::class);
  }
  
  
  // ACCESSORS
  public function getTheImageAttribute() {
    return (!$this->image) ? asset('dashboard/assets/images/placeholder.jpeg') : asset('storage') . "/" . $this->image ;
  }
  
  public function getTheNameAttribute() {
    return ($this->parent) ? $this->parent->name . " — " . $this->name : $this->name ;
  }
  
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller {

    public function index() {
        return view('dashboard.home.index');
    }

}

app/Http/Controllers/DataTableController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

// MODELS
use App\Models\Product;
use App\Models\Category;
use App\Models\Brand;

class DataTableController extends Controller {
  
  // FETCH PRODUCTS
  public function fetch_products(Request $request) {
    if($request->ajax()) {
      // GET PRODUCTS
      if($request->get('query')) {
        $products = Product::where('name', 'like', '%' . $query = $request->get('query') . '%')->where('status', 'published')->paginate(10);
      }
      else {
        $products = Product::where('status', 'published')->orderBy('name', 'asc')->paginate(10);
      }
      
      // SET SELECTED AS ARRAY
      $selected = explode(",", $request->get('selected'));

      return view('dashboard.datatables.products', compact('products', 'selected'))->render();
    }
  }
  
  // FETCH SELECTED PRODUCTS
  public function fetch_selected_products(Request $request) {
    if($request->ajax()) {
      // SET SAVED AS ARRAY
      $saved = explode(",", $request->get('saved'));

      // GET PRODUCTS
      $products = Product::whereIn('id', $saved)->get();

      return view('dashboard.datatables.selected_products', compact('products'))->render();
    }
  }
  
  // FETCH CATEGORIES
  public function fetch_categories(Request $request) {
    if($request->ajax()) {
      // GET CATEGORIES
      if($request->get('query')) {
        $categories = Category::where('name', 'like', '%' . $request->get('query') . '%')->paginate(10);
      }
      else {
        $categories = Category::paginate(10);
      }
      
      // SET SELECTED AS ARRAY
      $selected = explode(",", $request->get('selected'));

      return view('dashboard.datatables.categories', compact('categories', 'selected'))->render();
    }
  }
  
  // FETCH SELECTED CATEGORIES
  public function fetch_selected_categories(Request $request) {
    if($request->ajax()) {
      // SET SAVED AS ARRAY
      $saved = explode(",", $request->get('saved'));

      // GET CATEGORIES
      $categories = Category::whereIn('id', $saved)->get();

      return view('dashboard.datatables.selected_categories', compact('categories'))->render();
    }
  }
  
  // FETCH BRANDS
  public function fetch_brands(Request $request) {
    if($request->ajax()) {
      // GET BRANDS
      if($request->get('query')) {
        $brands = Brand::where('name', 'like', '%' . $request->get('query') . '%')->paginate(10);
      }
      else {
        $brands = Brand::paginate(10);
      }
      
      // SET SELECTED AS ARRAY
      $selected = explode(",", $request->get('selected'));

      return view('dashboard.datatables.brands', compact('brands', 'selected'))->render();
    }
  }
  
  // FETCH SELECTED BRANDS
  public function fetch_selected_brands(Request $request) {
    if($request->ajax()) {
      // SET SAVED AS ARRAY
      $saved = explode(",", $request->get('saved'));

      // GET BRANDS
      $brands = Brand::whereIn('id', $saved)->get();

      return view('dashboard.datatables.selected_brands', compact('brands'))->render();
    }
  }
  
}

resources/views/dashboard/datatables/brands.blade.php
@if(!$brands->isEmpty())
  
  @foreach($brands as $brand)
  <tr>
    <td class="align-middle text-center">
      <input type="checkbox"
             class="form-check-input"
             value="{{ $brand->id }}"
             @foreach($selected as $id)
               @if($id == $brand->id) checked @endif
             @endforeach />
    </td>
    <td>
      <div class="d-flex align-items-center">
        <img class="me-4" src="{{ $brand->the_image}}" width="40" height="40" alt="" />
        
        <div>
          {{ $brand->name }}
        </div>
      </div>
    </td>
  </tr>
  @endforeach

  <tr>
    <td colspan="2">
      <div class="p-0 pt-4">
        {{ $brands->links() }}
      </div>
    </td>
  </tr>

@else

  <tr>
    <td colspan="2">
      <div class="p-5 text-center">
        Item not found.
      </div>
    </td>
  </tr>

@endif

resources/views/dashboard/datatables/categories.blade.php
@if(!$categories->isEmpty())
  
  @foreach($categories as $category)
  <tr>
    <td class="align-middle text-center">
      <input type="checkbox"
             class="form-check-input"
             value="{{ $category->id }}"
             @foreach($selected as $id)
               @if($id == $category->id) checked @endif
             @endforeach />
    </td>
    <td>
      <div class="d-flex align-items-center">
        <img class="me-4" src="{{ $category->the_image}}" width="40" height="40" alt="" />
        
        <div>
          {{ $category->the_name }}
        </div>
      </div>
    </td>
  </tr>
  @endforeach

  <tr>
    <td colspan="2">
      <div class="p-0 pt-4">
        {{ $categories->links() }}
      </div>
    </td>
  </tr>

@else

  <tr>
    <td colspan="2">
      <div class="p-5 text-center">
        Item not found.
      </div>
    </td>
  </tr>

@endif

resources/views/dashboard/datatables/products.blade.php
@if(!$products->isEmpty())
  
  @foreach($products as $product)
  <tr>
    <td class="align-middle text-center">
      <input type="checkbox"
             class="form-check-input"
             value="{{ $product->id }}"
             @foreach($selected as $id)
               @if($id == $product->id) checked @endif
             @endforeach />
    </td>
    <td>
      <div class="d-flex align-items-center">
        <img class="me-4" src="{{ $product->the_image}}" width="40" height="40" alt="" />
        
        <div>
          {{ $product->name }}
          <div class="sa-meta mt-0">
            <ul class="sa-meta__list">
              <li class="sa-meta__item">SKU: {{ $product->sku->sku }}</li>
              <li class="sa-meta__item">MFG#: {{ $product->sku->mfg_part_number }}</li>
            </ul>
          </div>
        </div>
      </div>
    </td>
  </tr>
  @endforeach

  <tr>
    <td colspan="2">
      <div class="p-0 pt-4">
        {{ $products->links() }}
      </div>
    </td>
  </tr>

@else

  <tr>
    <td colspan="2">
      <div class="p-5 text-center">
        Item not found.
      </div>
    </td>
  </tr>

@endif

resources/views/dashboard/datatables/selected_brands.blade.php
@if(!$brands->isEmpty())
  
  @foreach($brands as $brand)
  <tr>
    <td>
      <div class="d-flex align-items-center">
        <img class="me-4" src="{{ $brand->the_image}}" width="40" height="40" alt="" />
        
        <div>
          {{ $brand->name }}
        </div>
      </div>
    </td>
  </tr>
  @endforeach
  
  <tr>
    <td>
      <a class="clear-brands text-danger" role="button">
        Clear brands
      </a>
    </td>
  </tr>

@else

  <tr>
    <td>
      <div class="p-5 text-center">
        Item not found.
      </div>
    </td>
  </tr>

@endif

resources/views/dashboard/datatables/selected_categories.blade.php
@if(!$categories->isEmpty())
  
  @foreach($categories as $category)
  <tr>
    <td>
      <div class="d-flex align-items-center">
        <img class="me-4" src="{{ $category->the_image}}" width="40" height="40" alt="" />
        
        <div>
          {{ $category->the_name }}
        </div>
      </div>
    </td>
  </tr>
  @endforeach
  
  <tr>
    <td>
      <a class="clear-categories text-danger" role="button">
        Clear categories
      </a>
    </td>
  </tr>

@else

  <tr>
    <td>
      <div class="p-5 text-center">
        Item not found.
      </div>
    </td>
  </tr>

@endif

resources/views/dashboard/datatables/selected_products.blade.php
@if(!$products->isEmpty())
  
  @foreach($products as $product)
  <tr>
    <td>
      <div class="d-flex align-items-center">
        <img class="me-4" src="{{ $product->the_image }}" width="40" height="40" alt="" />
        
        <div>
          {{ $product->name }}
          <div class="sa-meta mt-0">
            <ul class="sa-meta__list">
              <li class="sa-meta__item">SKU: {{ $product->sku->sku }}</li>
              <li class="sa-meta__item">MFG#: {{ $product->sku->mfg_part_number }}</li>
            </ul>
          </div>
        </div>
      </div>
    </td>
  </tr>
  @endforeach
  
  <tr>
    <td>
      <a class="clear-products text-danger" role="button">
        Clear products
      </a>
    </td>
  </tr>

@else

  <tr>
    <td>
      <div class="p-5 text-center">
        Item not found.
      </div>
    </td>
  </tr>

@endif